# -*- coding: utf-8 -*-
"""Apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5a7ASCgGEbdRobXt_EStePdzHE4gTJy
"""

import pandas as pd
import numpy as np

df=pd.read_csv(r"/content/Market_Basket_Optimisation.csv")
df.info()

df.head(5)

df.tail(5)

for col in df.columns:
  print(df[col].name,df[col].isnull().sum())

df.size

df.shape

df.describe()

len(df)

len(df.columns)

transactions=[]
for i in range(0,len(df)):
  transactions.append([str(df.values[i,j]) for j in range(0,len(df.columns)) if str(df.values[i,j])!='0'])

!pip install apyori

from apyori import apriori
rules=apriori(transactions=transactions,min_support=0.003,min_confidence=0.2,min_lift=3,min_length=2,max_length=2)

result=list(rules)
result

from apyori import apriori
rules=apriori(transactions=transactions,min_support=0.003,min_confidence=0.2,min_lift=3,min_length=2,max_length=2)
result=list(rules)
import pandas as pd
records = []
for r in result:
    for s in r.ordered_statistics:
        item_1 = list(s.items_base)[0]
        item_2 = list(s.items_add)[0]
        records.append({
            "item_1": item_1,
            "item_2": item_2,
            "support": r.support,
            "confidence": s.confidence,
            "lift": s.lift
        })

df = pd.DataFrame(records)
df